### ISSUE TITLE
Use of instance_variable_set in testing?

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/ruby_testing#1]
Is using `instance_variable_set` a code smell, when used only in testing? For example:

Is it better to have `@guess` as a parameter, to be able to easily create a new instance of game for tests `subject(:game) { described_class.new(0, 9, 4) }`

```
def initialize(min, max, guess = nil)
  @min = min
  @max = max
  @guess = guess
end
```

Or is it better to have less arguments and to use `game.instance_variable_set(:@guess, 4)` in the few tests that require a value for `@guess`?

```
def initialize(min, max)
  @min = min
  @max = max
  @guess = nil
end
```

**Comment by KevinMulhern** [comment]
@rlmoser99 yeah I believe that its a code smell and your solution of passing the param in during initialisation is how it should be done. It fits nicely with the open closed principle. Having to use instance_variable_set seems like a work around.

**Comment by rlmoser99** [comment]
Awesome! Thanks for your input! It is great to know with confidence that we should not be using `instance_variable_set` in testing.
