### ISSUE TITLE
Using send for private methods?

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/ruby_testing#2]
If you have a method that could be private, but should be tested, for example because it is sending an outgoing command message. Should it be public so that it is easily tested or private and use `send` in RSpec to test?

**Comment by KevinMulhern** [comment]
I don't think this is something we need to worry about.

The public methods should be using the private methods, so any private methods should be tested implicitly in the tests for the public methods.

**Comment by rlmoser99** [comment]
I believe the way that most students write code, not all private methods are tested implicitly in a public methods test. This is a "real world" expectation that does not work in these game projects (at least until we revamp the OOP lessons).

My original post did not explain the situation very clearly. Most student projects have a class where there is only one public entry point and the rest of the methods can technically be private. The one public method is usually a big long script, that is hard to test. 

For example, in the following file, all the method except `#play_game` can be private. However, for this project, I have opted to keep every method public that is included in a script method & should be tested. 
https://github.com/TheOdinProject/ruby_testing/blob/master/lib/15a_binary_game.rb

I just wanted to confirm that I should be keeping all of these methods public. As opposed to making these methods private and using `send` to test them.

Students are taught to keep everything private that is not needed to be public, so this creates confusion when it comes to testing these methods that can 'technically' be private, (but really should be public).

**Comment by KevinMulhern** [comment]
ahh I see what you mean, IMO this is a failure the earlier part of the course to teach separating those concerns. The idea we had about teaching the student to write a script which would handle the game loop and all the user interaction so the objects could be left to the game logic would be the approach to solve this in the long term.

I don't think we should be teaching students to use send to test private methods in the short term however as that would just be another bad habit we could get them into.

I think having all those methods public like you have is the way to go with this 👍

**Comment by rlmoser99** [comment]
Sounds good. Thanks for your input on this issue!
