### ISSUE TITLE
Bug - BinaryGame Spec: Comment indicating the method type for #display_turn_order is incorrect

### ISSUE THREAD

**Issue by wwrk22** [TheOdinProject/ruby_testing#40]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Exercises: File type incorrect for all test files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

**File**: `./spec/15a_binary_game_spec.rb`
**Example Group**: `describe '#display_turn_order' do`
**Issue**: The first comment line says `# This method is a Looping Script Method.` but this seems to be indicating the method type for `#display_binary_search` as shown in the comment `# Looping Script Method -> Test the behavior of the method (for example, it` under the example group `describe '#display_binary_search' do`.
The method `#display_turn_order` seems to be a combination of Command Method and Script Method. If this is correct then the lines:
```
# This method is a Looping Script Method. In #display_binary_search,
# #display_turn_order will loop until binary_search.game_over?
```
should be changed to something similar to:
```
# This method is both a Command Method and a Script Method. It changes the
# observable state by incrementing the instance variable @guess_count by one,
# sends two command messages #make_guess and #update_range to the
# object binary_search of class BinarySearch, and sends one command
# message to `self` by calling #display_guess.
```

**2. How To Reproduce:**

N/A

**3. Expected Behavior:**

N/A

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

N/A

**Comment by rlmoser99** [comment]
@wwrk22 Thanks for taking the time to make this issue. You are correct, this should be updated. I will go ahead and assign you to this issue, but since a month has passed, just let me know if you do not have time to do this and I will open it up to others.

**Comment by wwrk22** [comment]
> @wwrk22 Thanks for taking the time to make this issue. You are correct, this should be updated. I will go ahead and assign you to this issue, but since a month has passed, just let me know if you do not have time to do this and I will open it up to others.

Thanks for the assignment. I'll be able to get to it sometime today.
