### ISSUE TITLE
Bug - Relishapp Links not working

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/ruby_testing#41]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Exercises: File type incorrect for all test files`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Relishapp, which hosts docs for RSpec that are linked throughout these exercises, is down and has been continuously down for about a week. Given the length of the outage, I think it's a good idea to consider some alternative.

More potential context: [thread from r/ruby](https://www.reddit.com/r/ruby/comments/11czta1/relishapp_is_down_anyone_knows_what_happened/) on the outage

**2. How To Reproduce:**

Visit any link to [Relishapp](https://relishapp.com/)

**3. Expected Behavior:**

 N/A

**4. Desktop/Device:**
N/A

**5. Additional Information:**

- Maybe the simplest solution would be to replace the current links with a [Web Archive snapshot](https://web.archive.org/web/20230101143200/https://relishapp.com/) to relishapp.
- There are 39 relishapp links in this repo. You can list them by doing `grep -rno relishapp .` in the root of this repo. That output will show the filenames and line numbers for each relishapp link.

**Comment by CouchofTomato** [comment]
Thanks @JoshDevHub 

https://rspec.info/documentation/ looks like this will be a longer term issue as they are looking for a new host. We could do as they suggest and use the raw files on github or we could do a web archive snapshot as you suggest or we could link to the api https://rspec.info/documentation/3.12/rspec-core/

I'm open to feedback on this.
