### ISSUE TITLE
Replace Web Archive Links with RSpec Documentation

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/ruby_testing#49]
**Description:**
We no longer need to use web archive for rspec documentation. We can use the new site: http://rspec.info/features/3-12/rspec-expectations/built-in-matchers/

The following PR changed the links throughout this repository to the web archive links when the documentation site went down
https://github.com/TheOdinProject/ruby_testing/pull/42

**Acceptance Criteria:**

Replace each of the web archive links with an updated link. If needed use the above PR to help see the original links.

**Comment by MooseCowBear** [comment]
I can do it.
