### ISSUE TITLE
Spelling error at ./spec/14_final_number_spec.rb line 6.

### ISSUE THREAD

**Issue by NikEmman** [TheOdinProject/ruby_testing#53]
- [x] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure) *
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) *
- [x] Would you like to work on this issue?

Simple spelling error fix. Suggested change at line 6 as follows:
```diff
-# 1. Familarize
+# 1. Familiarize
```

**Comment by JoshDevHub** [comment]
Nice find. I've assigned you to work on this.

In the future, whenever you come across a small typo issue, you can just jump straight to submitting a PR for it. No need to make an issue, which will save you a little time/effort.

**Comment by NikEmman** [comment]
Yes I read that, apologies for the hussle. I just wanted to go through the whole process of opening an issue and then making a pull request for learning purposes.

I recently went through that git lesson in Ruby path so I took the opportunity to do the whole thing.

If I find a spelling mistake down the road I'll take the shortcut. Cheers!
